export default [
  {
    order: 0,
    key: 'UniversePage',
    component: 'Universes',
    question: 'In what universe is your movie played?',

    answer: 'You cannot go wrong with a good old {winner} movie',
    header: 'Story /<br /> Universes',
    keyword: 'universe',
  },
  {
    order: 1,
    key: 'GenrePage',
    component: 'Genres',
    question: 'What is the genre of your movie?',

    answer: 'You cannot go wrong with a good old {winner} movie',
    header: 'Story / <br/> Genres',
    keyword: 'genres',
    singleKeyword: 'genre_name',
    hasMany: true
  },
  {
    order: 2,
    key: 'OriginPage',
    component: 'Origins',
    question: 'Where does your story come from?',
  },
  {
    order: 3,
    key: 'SeriePage',
    component: 'Series',
    question: 'Is your movie part of a bigger story?',
  },
  {
    order: 4,
    key: 'LanguagePage',
    component: 'Languages',
    question: 'In what language should you tell the story?',
  },
  {
    order: 5,
    key: 'LeadActorGenderPage',
    component: 'LeadActorGenders',
    question: 'Who should your story resolve around?',
  },
  {
    order: 6,
    key: 'LeadActorAgePage',
    component: 'LeadActorAges',
    question: 'Who should your story resolve around?',
  },
  {
    order: 7,
    key: 'BudgetPage',
    component: 'Budgets',
    question: 'How much will you have to invest?',
  },
  {
    order: 8,
    key: 'DirectorGenderPage',
    component: 'DirectorGenders',
    question: 'Who should direct youre movie?',
  },
  {
    order: 9,
    key: 'DirectorAgePage',
    component: 'DirectorAges',
    question: 'Who should direct youre movie?',
  },
  {
    order: 10,
    key: 'CountryPage',
    component: 'Countries',
    question: 'Where should you produce the movie?',
  },
  {
    order: 11,
    key: 'CinematographyPage',
    component: 'Cinematographies',
    question: 'Should your movie be live action or an animation?',
  },
  {
    order: 12,
    key: 'LengthPage',
    component: 'Lengths',
    question: 'How long should your movie be?',
  },
  {
    order: 13,
    key: 'WordCountPage',
    component: 'Words',
    question: 'How much dialogue should there be?',
  },
  {
    order: 14,
    key: 'ReleaseMonthPage',
    component: 'Months',
    question: 'When should you release your movie?',
  },
  {
    order: 15,
    key: 'DistributionCompaniesPage',
    component: 'DistributionCompanies',
    question: 'Who should be responsible for the distribution?',
  },
  {
    order: 16,
    key: 'RestrictionPage',
    component: 'Restrictions',
    question: 'Who is your audience?',
  },
  {
    order: 17,
    key: 'PosterPage',
    component: 'Posters',
    question: 'How should the poster of the movie look?',
  },
  {
    order: 18,
    key: 'ResultsPage',
    component: 'Results',
    question: '',
  },
]
