export default [
  {
    // order: 0,
    key: 'UniversePage',
    component: 'Universes',
    question: 'In what universe is your movie played?',
  },
  {
    // order: 1,
    key: 'GenrePage',
    component: 'Genres',
    question: 'What is the genre of your movie?',
  },
  {
    // order: 2,
    key: 'OriginPage',
    component: 'Origins',
    question: 'Where does your story come from?',
  },
  {
    // order: 2,
    key: 'SeriePage',
    component: 'Series',
    question: 'Is your movie part of a bigger story?',
  },
  {
    // order: 2,
    key: 'LanguagePage',
    component: 'Languages',
    question: 'In what language should you tell the story?',
  },
  {
    // order: 2,
    key: 'LeadActorGenderPage',
    component: 'Genders',
    question: 'Who should your story resolve around?',
  },
  // {
  //   // order: 2,
  //   key: 'LeadActorAgePage',
  //   component: 'Ages',
  //   question: 'Who should your story resolve around?',
  // },
  // {
  //   // order: 2,
  //   key: 'BudgetPage',
  //   component: 'Budgets',
  //   question: 'How much will you have to invest?',
  // },
  // {
  //   // order: 2,
  //   key: 'DirectorGenderPage',
  //   component: 'Genders',
  //   question: 'Who should direct youre movie?',
  // },
  // {
  //   // order: 2,
  //   key: 'DirectorAgePage',
  //   component: 'Ages',
  //   question: 'Who should direct youre movie?',
  // },
  // {
  //   // order: 2,
  //   key: 'CountryPage',
  //   component: 'Countries',
  //   question: 'Where should you produce the movie?',
  // },
  // {
  //   // order: 2,
  //   key: 'CinematographyPage',
  //   component: 'Cinematographies',
  //   question: 'Should your movie be live action or an animation?',
  // },
  // {
  //   // order: 2,
  //   key: 'LengthPage',
  //   component: 'Lengths',
  //   question: 'How long should your movie be?',
  // },
  // {
  //   // order: 2,
  //   key: 'WordPage',
  //   component: 'Words',
  //   question: 'How much dialogue should there be?',
  // },
  // {
  //   // order: 15,
  //   key: 'ReleaseMonthPage',
  //   component: 'Months',
  //   question: 'When should you release your movie?',
  // },
  // // {
  // //   // order: 2,
  // //   key: 'DistributionCompaniesPage',
  // //   component: 'DistributionCompanies',
  // //   question: 'Who should be responsible for the distribution?',
  // // },
  // {
  //   // order: 2,
  //   key: 'RestrictionPage',
  //   component: 'Restrictions',
  //   question: 'Who is your audience?',
  // },
  // {
  //   // order: 2,
  //   key: 'PostePage',
  //   component: 'Posters',
  //   question: 'How should the poster of the movie look?',
  // },

  {
    // order: 19,
    key: 'ResultsPage',
    component: 'Results',
    question: '',
  },
]
